### ISSUE TITLE
Registration - email fields

### ISSUE THREAD

**Issue by matuskrizo** [Wradgio/StretchShop#14] opened 2020-01-05 19:25 UTC
When I try to register with incorrect email and email conform fields, I get error. This scenario is correct. But when I retype correct email address, error is still there - Values do not match.

**Comment by matuskrizo** [comment] 2020-01-05 19:29
Aaaand there is something worst - I am logged in. I see error, I don´t get any confirm email and I´m logged in not existing account.

**Comment by Wradgio** [comment] 2020-01-13 18:29
Please can you write me steps to reproduce. I am having a hard time reproducing it.

**Comment by matuskrizo** [comment] 2020-01-13 19:09
When I try reproduce this issue, everything works fine now. Maybe is this fixed already.

**Comment by Wradgio** [comment] 2020-02-05 08:23
Closing - unable to reproduce.

**Closed by Wradgio** 2020-02-05 08:23 UTC
